README.md
Currently:
Now: :mindblown:
See: https://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown/21521184#21521184
=> Fix broken SVG image on npmjs

examples/ios/objectivec/TypewriterExample/Analytics/SEGKicksAppAnalytics.m, examples/ios/objectivec/TypewriterExample/ViewController.m, examples/js/pages/generated/index.js, examples/node/generated/index.js, src/commands/gen-ios.ts, src/commands/gen-js.ts, tests/commands/ios/__snapshots__/SEGTestTrackingPlanAnalytics.m, tests/commands/js/__snapshots__/index.amd.js, tests/commands/js/__snapshots__/index.js, tests/commands/js/__snapshots__/index.node.js, tests/commands/js/__snapshots__/index.system.js, tests/commands/js/__snapshots__/index.umd.js
Setting the Typewriter context fields in `library` overwrote the `library.*` fields. This moves those fields in our JS library out to `context.typewriter` and adds these fields to iOS.
Skipping TypeScript for now, since we'll likely update it to use JS in #26 
Skipping Android for now, until https://github.com/segmentio/analytics-android/pull/595 is released in the next analytics-android release
=> [SCH-1225] Move Typewriter context fields out of library; add to iOS

examples/gen-android/java/README.md, examples/gen-android/java/app/src/main/AndroidManifest.xml, examples/gen-android/java/app/src/main/java/com/segment/typewriterexample/MainActivity.java, examples/gen-android/java/app/src/main/java/com/segment/typewriterexample/TypewriterApplication.java
The Android example was misconfigured to regenerate an Analytics instance every time the `MainActivity` was loaded. This moves this logic into the `Application` class where it will only be executed once, following analytics-android best practices.
=> fix: crash in Android example on back button

examples/gen-js/js/analytics/generated/index.d.ts, examples/gen-js/node/analytics/generated/index.d.ts, examples/gen-js/ts/analytics/generated/index.d.ts, src/commands/gen-js/typescript.ts, tests/commands/gen-js/__snapshots__/index.d.ts, tests/commands/gen-js/__snapshots__/index.node.d.ts
This adds `integrations` to the Node.JS TypeScript declarations, along with `AppsFlyer` as an exception. This also adds `All` as a convenience.
=> fix: add integrations to node.js and support the AppsFlyer exception [SCH-1407]

package.json, yarn.lock
Hey TypeWriter team!
This PR moves `typescript` into regular ol' production `"dependencies"`. I believe importing it the dist lib causes problems when consumers install using `yarn install --production` mode.
The problem might be exacerbated by the fact that I'm using `typescript` as a dev-dep in this project, too. Hard to tell.
=> move typescript to a production dep

examples/gen-js/ts/components/Layout.tsx, examples/gen-js/ts/components/Modal.tsx, examples/gen-js/ts/pages/index.tsx, examples/gen-js/ts/tsconfig.json, src/commands/gen-android.ts, src/commands/gen-ios.ts, src/commands/gen-js/index.ts, src/commands/gen-js/library.ts, src/commands/gen-js/typescript.ts, src/global.d.ts, src/lib/utils.ts, tests/commands/gen-js/__snapshots__/index.node.d.ts, tsconfig.json
This PR fixes an issue seen by Typewriter-users where the optional types introduced in https://github.com/segmentio/typewriter/pull/39 cause `strictNullChecks` errors during builds:
```
integrations?: {
All?: boolean
AppsFlyer?: {
appsFlyerId: string
}
// Adds `| undefined`
[key: string]: boolean | { [key: string]: string } | undefined
}
```
```
#!/bin/bash -eo pipefail
yarn build
yarn run v1.6.0
$ make build
./node_modules/.bin/tsc && rsync -am --include='*.graphql' --include='*/' --exclude='*' src dist
src/lib/typewriter/generated/index.d.ts:54:5 - error TS2411: Property 'All' of type 'boolean | undefined' is not assignable to string index type 'boolean | { [key: string]: string; }'.
54     All?: boolean;
~~~
src/lib/typewriter/generated/index.d.ts:55:5 - error TS2411: Property …
```
=> Enable strict + fix `strictNullCheck` TS errors

package.json, yarn.lock
This PR fixes the `release-it` configuration which was failing to publish due to a deprecated configuration. It also fixes the `commitlint` setup which was accepting invalid commit names.
I'll release 5.1.3 when this merges.
=> fix: update release-it 7 -> 10

examples/gen-js/js/analytics/generated/index.d.ts, examples/gen-js/ts/analytics/generated/index.d.ts, src/commands/gen-js/typescript.ts, tests/commands/gen-js/__snapshots__/index.d.ts
This replicates the fix from: #43 in the `analytics.js` library, which was mistakenly left out of the previous PR.
=> fix: apply strictNullCheck fix in analytics.js client

examples/gen-js/js/analytics/generated/index.d.ts, examples/gen-js/js/analytics/generated/index.js, examples/gen-js/node/analytics/generated/index.d.ts, examples/gen-js/node/analytics/generated/index.js, examples/gen-js/ts/analytics/generated/index.d.ts, examples/gen-js/ts/analytics/generated/index.js, src/commands/gen-js/library.ts, src/commands/gen-js/typescript.ts, tests/commands/gen-js/__snapshots__/index.amd.js, tests/commands/gen-js/__snapshots__/index.d.ts, tests/commands/gen-js/__snapshots__/index.es5.js, tests/commands/gen-js/__snapshots__/index.es5.node.js, tests/commands/gen-js/__snapshots__/index.node.d.ts, tests/commands/gen-js/__snapshots__/index.node.js, tests/commands/gen-js/__snapshots__/index.prod.js, tests/commands/gen-js/__snapshots__/index.prod.node.js, tests/commands/gen-js/__snapshots__/index.system.js, tests/commands/gen-js/__snapshots__/index.umd.js, tests/commands/gen-js/library.test.ts
This makes `message` an optional parameter for auto-generated `track` calls, allowing you to make calls in `ts`-compiled files without passing in a message:
```
typewriter.fooBar()
```
instead of:
```
typewriter.fooBar({})
```
----
This also adds tests for ES5-transpiled clients (in this case, to validate that optional parameters were transpiled).
=> fix: optional message parameter in JS clients

examples/gen-js/js/analytics/generated/index.d.ts, examples/gen-js/node/analytics/generated/index.d.ts, examples/gen-js/ts/analytics/generated/index.d.ts, src/commands/gen-js/typescript.ts, tests/commands/gen-js/__snapshots__/index.d.ts, tests/commands/gen-js/__snapshots__/index.node.d.ts
Hey typewriters! 👋 
This PR adds an explicitly-typed `Context` export for both node and ajs _and_ includes it in the track signature's `options` argument
=> fix: include `context` typedef for both node and ajs top levels

examples/gen-js/js/analytics/generated/index.d.ts, examples/gen-js/ts/analytics/generated/index.d.ts, src/commands/gen-js/typescript.ts, tests/commands/gen-js/__snapshots__/index.d.ts
Turns out _all_ `SegmentOptions` properties should be optional. 😄
=> fix: all SegmentOptions should be optional

examples/gen-js/js/analytics/generated/index.js, examples/gen-js/node/analytics/generated/index.js, examples/gen-js/ts/analytics/generated/index.js, src/commands/gen-js/library.ts, tests/commands/gen-js/__snapshots__/index.amd.js, tests/commands/gen-js/__snapshots__/index.es5.js, tests/commands/gen-js/__snapshots__/index.es5.node.js, tests/commands/gen-js/__snapshots__/index.js, tests/commands/gen-js/__snapshots__/index.node.js, tests/commands/gen-js/__snapshots__/index.prod.js, tests/commands/gen-js/__snapshots__/index.prod.node.js, tests/commands/gen-js/__snapshots__/index.system.js, tests/commands/gen-js/__snapshots__/index.umd.js
BREAKING CHANGE: if you previously passed `context` directly as the final
parameter to the `analytics.js` or `analytics-node` clients, then you'll
need to update it, like so:
If you made a call like:
```
typewriter.thingHappened({ when: 'now' }, { groupId: 123 })
```
Then you would need to update it to:
```
typewriter.thingHappened({ when: 'now' }, {
context: { groupId: 123 }
})
```
This allows you to pass `integrations` and other fields in through this
object, and aligns the TypeScript declarations with the underlying library.
=> fix: javascript clients accepted context rather than options

examples/gen-js/js/analytics/generated/index.d.ts, examples/gen-js/js/analytics/generated/index.js, examples/gen-js/node/analytics/generated/index.d.ts, examples/gen-js/node/analytics/generated/index.js, examples/gen-js/ts/analytics/generated/index.d.ts, examples/gen-js/ts/analytics/generated/index.js, src/commands/gen-js/library.ts, src/commands/gen-js/typescript.ts, tests/commands/gen-js/__snapshots__/index.amd.js, tests/commands/gen-js/__snapshots__/index.d.ts, tests/commands/gen-js/__snapshots__/index.es5.js, tests/commands/gen-js/__snapshots__/index.es5.node.js, tests/commands/gen-js/__snapshots__/index.js, tests/commands/gen-js/__snapshots__/index.node.d.ts, tests/commands/gen-js/__snapshots__/index.node.js, tests/commands/gen-js/__snapshots__/index.prod.js, tests/commands/gen-js/__snapshots__/index.prod.node.js, tests/commands/gen-js/__snapshots__/index.system.js, tests/commands/gen-js/__snapshots__/index.umd.js
From integrating Typewriter at Segment, we've learned that throwing an error whenever Typewriter discovers a validation issues is a pretty poor DX because it forces you to align your instrumentation and spec from day 1. Instead, we want to offer developers the opportunity to iteratively adopt Typewriter.
To do so, this PR exposes an `onError` handler that can be configured at run-time when constructing an instance of a Typewriter client.
As an example, this is what happens now when you have a validation error:
Your entire app breaks while developing locally -- and that interrupts your developer flow.
Now, you can hook in to that error handling logic like so:
```js
const analytics = new Analytics(window.analytics, {
onError: (error) => {
console.error(JSON.stringify(error, null, 2))
}
}) …
```
=> feat: custom error handlers

examples/gen-ios/objectivec/TypewriterExample/Analytics/SEGKicksAppAnalytics.h, package.json, src/commands/gen-ios.ts, tests/commands/gen-ios/__snapshots__/SEGTestTrackingPlanAnalytics.h, yarn.lock
Resolves an issue in iOS clients for required numeric values where the incorrect value was supplied to `analytics-ios`.
=> fix(iOS): assign -> copy for numeric types

.snyk, Makefile, package.json, yarn.lock
This PR updates the `handlebars` dependency.
It also updates the `pre-commit` hook to run typewriter's `build` instead of `update`, both a) so that you don't need to be a Segmenter to commit and b) so that changes to the Tracking Plan are opt-in rather than added on every commit.
=> Run `snyk wizard` and bump handlebars

Makefile, package.json
This PR changes the error message that is generated when running typewriter's test suite locally without `segmentio/mock` running.
=> Improve testing error when segmentio/mock is not running

src/generators/ios/ios.ts, tests/e2e/ios-objc/TypewriterExample/Analytics/SEGTypewriterAnalytics.h, tests/e2e/ios-objc/TypewriterExample/Analytics/SEGTypewriterAnalytics.m, tests/e2e/ios-objc/TypewriterExample/Analytics/plan.json, tests/e2e/ios-objc/TypewriterExampleTests/TypewriterExampleTests.m, tests/e2e/ios-swift/TypewriterSwiftExample/Analytics/SEGTypewriterAnalytics.h, tests/e2e/ios-swift/TypewriterSwiftExample/Analytics/SEGTypewriterAnalytics.m, tests/e2e/ios-swift/TypewriterSwiftExample/Analytics/plan.json, tests/e2e/ios-swift/TypewriterSwiftExampleTests/TypewriterSwiftExampleTests.swift, tests/e2e/node-javascript/analytics/index.js, tests/e2e/node-javascript/analytics/plan.json, tests/e2e/node-javascript/index.js, tests/e2e/node-typescript/analytics/index.ts, tests/e2e/node-typescript/analytics/plan.json, tests/e2e/node-typescript/index.ts, tests/e2e/suite.test.ts, tests/e2e/web-javascript/analytics/index.js, tests/e2e/web-javascript/analytics/plan.json, tests/e2e/web-javascript/pages/index.jsx, tests/e2e/web-typescript/analytics/index.ts, tests/e2e/web-typescript/analytics/plan.json, tests/e2e/web-typescript/pages/index.tsx
This PR adds a test to catch a regression we saw in our Swift client in v6 of typewriter, where an incorrect memory attribute led to corruption during serialization: https://github.com/segmentio/typewriter/pull/61/files
---
While adding this test, I noticed our iOS clients generate `NSInteger *` which is just a pointer to a primitive `int` under-the-hood. This PR updates the generator to instead us an `NSNumber *` for nullable and optional integers.
=> Add e2e test for large integers and floats

tests/e2e/suite.test.ts
This PR changes the error message that is generated when running typewriter's test suite locally without `segmentio/mock` running.
=> Update test suite conditional logic to use `if` instead of `skip`

.circleci/config.yml, package.json, yarn.lock
This PR removes a few unused dependencies and bumps Handlebars to remediate a Snyk vulnerability.
Currently trying to debug why Snyk is failing to parse this valid `package.json` with a `Failed to create project` error. This PR also removes the `"snyk": true` which may be responsible for that. I've removed Snyk from the CI config in favor of the Github integration.
=> Remove unused dependencies

.circleci/config.yml, Makefile
The iOS tests bottleneck our entire CI test suite, since they rely on us pulling down the Cocoapods spec cache. We can likely put our own cache up that has just analytics-ios.
For now, we can improve the iOS test suite time (and therefore, the entire test suite) by running dev and prod in parallel. This reduces iOS tests by about 2m, or ~15%.
We may need to adjust CI parallelism, TBD.
https://github.com/segmentio/typewriter/issues/99
=> [CI] Run dev and prod CI tests in parallel (~15% faster)

package.json
`prerelease` appears to be a `np` hook, which is causing `yarn release` to perform a pre-release
=> [development] Rename prerelease script to release:pre

package.json
Because of `master` branch protection, we can't do a release there. Instead:
- Check out the latest `master` with your merged PRs
- Check out a new branch `release/<new version number>`
- `yarn release`
- Fill out the release draft and publish it
- Push up branch as a PR and merge to `master`
=> Release non-pre-releases on release branches instead of master

examples/gen-android/java/.gitignore, examples/gen-android/java/app/src/main/java/com/segment/generated/KicksAppAnalytics.java, examples/gen-android/java/app/src/main/java/com/segment/generated/OrderCompleted.java, examples/gen-android/java/app/src/main/java/com/segment/generated/Product.java, examples/gen-android/java/app/src/main/java/com/segment/typewriterexample/DisplayMessageActivity.java, examples/gen-android/java/app/src/main/java/com/segment/typewriterexample/MainActivity.java, examples/gen-android/java/app/src/main/res/layout/activity_display_message.xml, examples/gen-android/java/app/src/main/res/layout/activity_main.xml, examples/gen-android/java/build.gradle, examples/gen-android/java/gradle.properties, examples/gen-android/java/gradle/wrapper/gradle-wrapper.properties, src/commands/gen-android.ts, tests/commands/gen-android/__snapshots__/ExampleEvent.java, tests/commands/gen-android/__snapshots__/OptionalArray.java, tests/commands/gen-android/__snapshots__/OptionalObject.java, tests/commands/gen-android/__snapshots__/RequiredArray.java, tests/commands/gen-android/__snapshots__/RequiredObject.java, tests/commands/gen-android/__snapshots__/TestTrackingPlanAnalytics.java, tests/commands/gen-android/__snapshots__/The42_TerribleEventName3.java
This PR migrates the android generator on v6 to generate annotations using the `androidx` library instead of the unmaintained `android.support` package. This PR also updates the example app to use `androidx`.
=> Migrate v6 Android client to `androidx` from `android.support`

src/generators/ios/ios.ts, tests/e2e/ios-objc/Podfile, tests/e2e/ios-objc/Podfile.lock, tests/e2e/ios-objc/TypewriterExample/Analytics/SEGOptionalArrayWithPropertiesItem.m, tests/e2e/ios-objc/TypewriterExample/Analytics/SEGOptionalArrayWithPropertiesItem1.m, tests/e2e/ios-objc/TypewriterExample/Analytics/SEGOptionalObjectWithProperties.m, tests/e2e/ios-objc/TypewriterExample/Analytics/SEGOptionalObjectWithProperties1.m, tests/e2e/ios-objc/TypewriterExample/Analytics/SEGTypewriterAnalytics.m, tests/e2e/ios-objc/TypewriterExampleTests/TypewriterExampleTests.m, tests/e2e/ios-swift/Podfile, tests/e2e/ios-swift/Podfile.lock, tests/e2e/ios-swift/TypewriterSwiftExample/Analytics/SEGOptionalArrayWithPropertiesItem.m, tests/e2e/ios-swift/TypewriterSwiftExample/Analytics/SEGOptionalArrayWithPropertiesItem1.m, tests/e2e/ios-swift/TypewriterSwiftExample/Analytics/SEGOptionalObjectWithProperties.m, tests/e2e/ios-swift/TypewriterSwiftExample/Analytics/SEGOptionalObjectWithProperties1.m, tests/e2e/ios-swift/TypewriterSwiftExample/Analytics/SEGTypewriterAnalytics.m, tests/e2e/ios-swift/TypewriterSwiftExampleTests/TypewriterSwiftExampleTests.swift, tests/e2e/suite.test.ts
`analytics-ios` recently released support for serializing `null` values in the request sent to the Segment Tracking API: https://github.com/segmentio/analytics-ios/issues/852
This was released as `v3.8.0-beta.1`. For folks using typewriter + `analytics-ios` of at least that version, null values for required fields will now be serialized. Optional fields set to `nil` continue to be removed before serialization.
Fixes https://github.com/segmentio/typewriter/issues/114
=> Update iOS E2E Test to reflect null serialization support

example/package.json, package.json, tests/e2e/web-javascript/package.json, tests/e2e/web-typescript/package.json, yarn.lock
the `ink`, `ink-link`, `ink-select-input`,  `ink-spinner`,  `and ink-text-input` deps don't work with `react`  17
=>  Fix: roll back react to work with ink

src/cli/index.tsx, src/generators/javascript/templates/segment.hbs
- makes either `userId` or `anonymousId` required rather than optional for both. 
- Adds a dummy `anonymousId` type to errorFired method since anonymousId is now a declared type.
=> fix: add identity type to make ids conditional

package.json
Fixes a typo in `package.json` for `typescript` package version.
=> Fix: TypeScript version

src/config/scripts.ts
On Windows, the following command fails to execute properly due to a parsing issue in Command Prompt, the default command line executor for Node:
```ts
const scriptWithCD = `cd ${configPath}; ${script}`;
```
This prevents Windows users from running `typewriter` in configurations that rely on script execution.
This PR switches from the semicolon to a boolean AND (`&&`) which works the same way on Windows and *nix. It does technically change the behavior though: a semicolon on *nix will run both sides of the semicolon regardless of the exit code of the left-hand side. This change does require that the left-hand side execute and return a zero exit status, which is probably a safe thing to ensure regardless.
Fixes #233
Before:
```
> npx typewriter update
× Error: Token script failed
→ Tried …
```
=> fix: use boolean AND to support scripts on Windows

src/common/ttys.ts
It is highly appreciated that you take the time to help improve Typewriter.
We appreciate it if you would take the time to document your Pull Request.
Sadly, if we don't receive enough information, or the Pull Request doesn't
align well with our roadmap, we might respectfully thank you for your time, and close the issue.
Please respect our [Code of Conduct](CODE_OF_CONDUCT.md), in short:
* Using welcoming and inclusive language.
* Being respectful of differing viewpoints and experiences.
* Gracefully accepting constructive criticism.
* Focusing on what is best for the community.
* Showing empathy towards other community members.
=> fix: reset to process.stdin/stdout when /dev/tty is not available

src/__tests__/commands/__snapshots__/build.test.ts.snap, src/__tests__/commands/__snapshots__/production.test.ts.snap, src/api/api.ts, src/api/trackingplans.ts, src/base-command.ts, src/commands/build.ts, src/languages/quicktype-utils.ts, src/languages/templates/typescript/analytics-js.hbs, src/languages/templates/typescript/node.hbs, src/telemetry/segment.ts
Fixes the validate against schema function calls on dev mode builds for AJS and Node generators.
Refactored the cleanups we do to the JSONSchema and added an extra step for replacing `id` with `$id` per JSONSchema draft 7 spec to play correctly with new versions of AJV.
=> fix: validateAgainstSchema called on dev mode

src/api/api.ts
Handles the redirection of `api.segmentapis.com` to `eu1.api.segmentapis.com` properly by attaching the authorization headers when required. For security we still match that the base domain is the same across redirects. 
By default `got` will strip the authorization when the redirect happens to a different hostname, this makes it slightly less strict by permitting subdomains.
=> fix: redirect support for EU Workspaces

src/api/trackingplans.ts
Modules with the 'node:' prefix are 18+, which prevents typewriter from running on other (still maintained) versions of Node. 
Admittedly these versions are on borrowed time, 14 is supported until April and 16 is supported until September.
=> fix: compatibility with node 14-16
